### ISSUE TITLE
Returning Null when used in BlockListEditor

### ISSUE THREAD

**Issue by pariashiri1984** [skartknet/Iconic#11]
I have used the package in two different components, one of them doesn't use the BlockList works without any problem locally and in the host, but the other one returns a null exception in the live site.
The structure of my component is like this:
- ItemBase => a composition as a base, it has an IconPicker 
 -- SimpleItem => Uses ItemBase
 -- ComplexItem => Uses ItemBase
 --- Menu => has a block list that have SimpleItem and ComplexItem inside
 
When it wants to render them just throw a null exception that there is no icon. The weirdest part is, that there is no issue locally that error is happening on the live site.

**Comment by skartknet** [comment]
Hi @pariashiri1984 , did you end up finding the cause of this?
