### ISSUE TITLE
Can't use absolute path for CSS file

### ISSUE THREAD

**Issue by inversiondk** [skartknet/Iconic#19]
Just downloaded version 3.2.0 of this awesome package with Umbraco 10. In the documentation it states "You can use absolute or relative paths" for the CSS file. 
However - when you create your data type, you only get a local file picker with no option to select an absolute path. I have my font kit hosted at a CDN and would very much like to use this option. 
Is this new functionality by design? 

Thanks a lot :)

**Comment by skartknet** [comment]
Hi @inversiondk , the first versions of Iconic had a textbox to enter the URL of your CSS file. To improve the user experience I decided to create the picker, and I missed the fact that a textbox would still be useful!

I'll fix that as soon as I can. Thank you for bringing that up.

**Comment by inversiondk** [comment]
@skartknet cool. It's not something that breaks the entire setup - I was just wondering. 
Very very cool little plugin. Thanks for creating it :)

**Comment by skartknet** [comment]
I have done some modifications to support this.... but I haven't tested it. Maybe someone can it it  try...?

I have created a version 4.1.0-beta with it.

**Comment by inversiondk** [comment]
I'll see if I can't give it a try with an upcoming project :)

**Comment by skartknet** [comment]
I have created a new version beta2, beta1 had a bug. You should see the input boxes.
![image](https://user-images.githubusercontent.com/1685262/191147000-418e8912-f906-4bd9-9a0a-c37acdc47f4b.png)

**Comment by onza22** [comment]
@skartknet Added beta2, when using the picker (select button) it then breaks the functionality?
![image](https://user-images.githubusercontent.com/32366840/191992802-a75a0002-fb12-4845-9577-ddd1d1818c06.png)
![image](https://user-images.githubusercontent.com/32366840/191993517-71690307-aeae-494a-b9dd-1bb3c0286d23.png)

@inversiondk how do you plan to use the kit, isn't the kit just a JS file?

**Comment by huwred** [comment]
I also get an isExternalUri is undefined using beta 2

**Comment by skartknet** [comment]
thanks guys, I have fixed that issue that @onza22 said, but I couldn't replicate the one from @huwred. It seems to be working fine now.

**Comment by skartknet** [comment]
I have created a beta3

**Comment by skartknet** [comment]
I have found the error for `isExternalUri`. I will fix this, don't test anything yet. Thanks.

**Comment by huwred** [comment]
> I have found the error for `isExternalUri`. I will fix this, don't test anything yet. Thanks.

Hi, any update on this one?

**Comment by skartknet** [comment]
I'm working on a new version with some other changes... and a new exciting feature ;). I hope I get it ready by the end of the week.

**Comment by skartknet** [comment]
I have created a beta4. Hopefully it works this time. I'm also shipping a few other improvements on this version like a Filter option. Still need to update the docs though.

**Comment by huwred** [comment]
:( beta4 seems to have broken it completely so had to revert back to beta 3. I will take a deeper look later and report back.

**Comment by huwred** [comment]
fixed the back office issue, I had to delete the old app_plugins folder, however I now get an error in the ui

`Unable to cast object of type 'Our.Iconic.IconicPackagesConfiguration' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.`

`   at Our.Iconic.Core.ConfiguredPackagesCollection.GetConfiguratedPackages(IPublishedPropertyType propertyType)
   at Our.Iconic.Core.ValueConverters.IconicValueConverter.ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview)
   at Umbraco.Cms.Core.Models.PublishedContent.PublishedPropertyType.ConvertInterToObject(IPublishedElement owner, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview)
   at Umbraco.Cms.Core.PublishedCache.PublishedElementPropertyBase.GetValue(String culture, String segment)
   at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback publishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Extensions.PublishedElementExtensions.Value[T](IPublishedElement content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Cms.Web.Common.PublishedModels.MenuItem.get_Icon() in E:\Umbraco-Dev\VantagePortal\VantagePortal.ContentModels\MenuItem.generated.cs:line 65`

**Comment by skartknet** [comment]
I'll take a look. Thanks for taking the time to test it.

**Comment by huwred** [comment]
All seems OK so far in the beta5

**Comment by skartknet** [comment]
I'll close this for now.
