### ISSUE TITLE
Overlay not opening correctly for infinite editing (Umbraco 10.2.0)

### ISSUE THREAD

**Issue by hfloyd** [skartknet/Iconic#20]
I just updated my website to Umbraco 10.2.0, and today I noticed that the iconic overlay was no longer usable - it doesn't open full-height:
![image](https://user-images.githubusercontent.com/1252593/189389427-7ea82e65-9af0-4656-bfd4-d1f4289aa34e.png)

Specifically my usage is of a nested Content Block property, using the default view with a "Medium" overlay:
![image](https://user-images.githubusercontent.com/1252593/189390195-ac7247e3-6b07-4b22-9051-fead1fac3db3.png)

I don't see any errors in the browser console.

I also tested by just putting the property onto a Content node, and when clicking on it the screen gets a transparent white overlay, but there is no iconic overlay visible.

Has anyone else noticed this?

**Comment by skartknet** [comment]
I was able to reproduce on a new 10.2.0 installation. Just a doctype with an Iconic property. The overlay doesn't open at all. I'm looking into it.

**Comment by Alaeddinalhamoud** [comment]
Same Issue :(

**Comment by skartknet** [comment]
I finally could take a look. The `UmbOverlay` directive has been deprecated for a long time now, and something in the version 10.2.0 has broken it. I have replaced it with the `overlayService`. It seems to be working now. Can you please give it a try?

The new version is v4.0.0

**Comment by hfloyd** [comment]
It works!!! Thanks so much for the quick fix, @skartknet 😊

**Comment by joshuacrittendenNFP** [comment]
No matter how I install 4.0, I'm still getting the old files, for instance "iconic.prevalues.editor.controller.js" only has 197 lines and "iconic.edit.dialog.html" only has 139... It all says 4.0 is installed. I even removed the package and reinstalled it.

**Comment by Alaeddinalhamoud** [comment]
> 

I have the same issue, 
Clean the project, delete bin and obj folders rebuild.
should be fine ;)

**Comment by joshuacrittendenNFP** [comment]
@Alaeddinalhamoud It works! Awesome, thank you!
