### ISSUE TITLE
Unable to select icons in the "Select an icon" overlay

### ISSUE THREAD

**Issue by RGV2ZWxvcGVy** [skartknet/Iconic#22]
I am using Umbraco version 10.3.2 in combination with Iconic version 5.0.1.
The Iconic package says the ".Core" version of the package is also required as a dependency, but it is not installed automatically when installing the main package. I have a clean install of Umbraco, and installed Font Awesome 5.15.4 as a client side library.

The configuration of the Iconic data type:

![image](https://user-images.githubusercontent.com/105918931/200840631-24d12ab4-c8b7-4ccb-9bbf-a0a0e6fbe799.png)

![image](https://user-images.githubusercontent.com/105918931/200840711-598f7a78-08fe-4a9e-9bb3-c9a74a71eb14.png)

When I try to pick an icon in the overlay, I get the following error message in the browser console:

![image](https://user-images.githubusercontent.com/105918931/200839907-5a2688bd-6c44-4d6e-be42-1a0d0fe2467b.png)

I tried this with and without the "Our.Iconic.Core" package, but I get the same results.

Expected behaviour:
The picked icon gets highlighted and picked correctly.

**Comment by PetervandenDungen** [comment]
Exact same issue here.

**Comment by wileyveteran** [comment]
Yep, $scope.value is undefined in Our.Iconic.Dialog.Controller
![image](https://user-images.githubusercontent.com/2445968/201263692-34739de7-6366-4817-b5de-5e67d7b8dffa.png)

**Comment by skartknet** [comment]
I have fixed this on version 5.1.0. I haven't been able to replicate any missing references to .Core though. I have installed the package in a fresh install and it has worked fine.

**Comment by skartknet** [comment]
BTW, I have removed the Override Backoffice checkbox. Just entering a value on the Backoffice Template input will indicate that you want to override the Template.

**Comment by RGV2ZWxvcGVy** [comment]
Thanks for the quick reply, and fix :)
