### ISSUE TITLE
Nullchecking is not wroking.

### ISSUE THREAD

**Issue by jordan-umbrace** [skartknet/Iconic#3]
Even when there is no Icon selected via the property, it renders.

```
@if (Html.Raw(content.ButtonIcon.ToString()) != null)
    {
        <div class="button-content is--icon-font">@Html.Raw(content.ButtonIcon) </div>
    }
```
Always renders

```
<div class="button-content is--icon-font"> </div>
```

Not sure if I'm doind something wrong

**Comment by skartknet** [comment]
Hey Jordan,
Apologies it took me so long to respond, but I wasn't receiving notifications from Github.
I hope you found out how to check if a value is not set. You can do this:
```
@if(string.IsNullOrEmpty(Model.Iconic.ToString()))
{
	<p>no icon!</p
}
