### ISSUE TITLE
Docs + Make Rules source file Mandatory

### ISSUE THREAD

**Issue by TRexStark** [skartknet/Iconic#30]
Hi @skartknet,

This is a fantastic icon Picker and I ditched mine that I created ages ago and decided to use your package, however, I think the Docs need a bit of updating from the screenshots point of view and maybe they need to be in the Marketplace? Or somewhere easy to find? - Just a suggestion - of course it's up to you. Due to how the entire ecosystem of umbraco, nuget, .Net Core etc now is different from the old days, I find myself sometimes just installing packages from nuget to test them out where some are straight forward and others require a bit of a setup.

Now back to the Rules source file:
Using v10 (latest), I was configuring the fonts and as a new user, I was confused as to why we have CSS File and Rules source file (Until I read the documentations). Maybe in this case the Rules source file should become mandatory? Because at start, I haven't added anything there and the DataType obviously didn't work - again (until I read the docs).

Otherwise, thank you for this Package.

**Comment by skartknet** [comment]
Hi @TRexStark ,

Thank you for using Iconic. You are right about the documentation. Screenshots need an update.

When you say 'the docs need to be in the marketplace', do you mean a link to the actual docs?:
![image](https://user-images.githubusercontent.com/1685262/227426927-81c1105a-b73e-4ac8-b643-f6240153dd2b.png)

I don't think the docs themselves can be on the marketplace, the description that appears there is more of a brief description of the package and maybe some quick tips about how to install it.

You are correct about the validation. In fact, I thought I made the Rules source file mandatory. I'll take a look.

Thanks for your suggestions!

**Comment by TRexStark** [comment]
Thanks @skartknet ... Not sure where the documentations could or should sit to be honest, i was just suggesting maybe the screenshots in the marketplace and basic directions, then a link to the full docs?

But again. Thank you.

**Comment by skartknet** [comment]
I have added a link to the Documentation on the marketplace and updated screenshots. Looking better now ;)
