### ISSUE TITLE
How to generate rules file?

### ISSUE THREAD

**Issue by AaronSadlerUK** [skartknet/Iconic#33]
Hi there!

What's the method to generate an updated rules file for Font Awesome 6?

Thanks!

**Comment by skartknet** [comment]
Hey @AaronSadlerUK ,

This is the solution I came up with:

Follow these instructions on the FA site: https://fontawesome.com/docs/web/setup/host-yourself/webfonts

The configuration for Iconic:
![image](https://github.com/skartknet/Iconic/assets/1685262/6306415f-5052-4868-814e-f655d5ff7033)

this is the config as json:
``` json
{
      "name": "Font Awesome 6 (Brands)",
      "selector": "\\.(fa-[\\w-]+):before {",
      "template": "<i class=\"fa-brands {icon}\"></i>"
}
```

BUT, there's a problem here. Font Awesome 6 needs 2 CSS files to work: `fontawesome.css` AND the icon-specific CSS, in this example would be `brands.css`. Iconic doesn't support configuring two CSS files for one package. So you have two options

1. Copy the content of `fontawesome.css` into `brands.css` 
2. Use the `all.css` instead. In this case, the regex will be: "\.(fa-[\w-]+)::before {" (note the double colon)

The second option will load a pretty big CSS, but you can use the separate files in your frontend, no need to use the `all.css`

I hope this helps.

**Comment by skartknet** [comment]
Hey Aaron, congrats on your MVP! ;)

Did you manage to configure this? I'll close it for now. Feel free to reopen if needed.

**Comment by AaronSadlerUK** [comment]
Thanks!

I haven't had a chance to try yet, I'll be sure to update this once I have
