### ISSUE TITLE
Can not load the css file in the content page Umbraco 9

### ISSUE THREAD

**Issue by OmarAlkylaney** [skartknet/Iconic#4]
Dear All,

I tried to use this plugin on my local site and it return a 404 with font css resources due it tries to load the css under the wwwroot and could not find it. Instead, it should load the css without the wwwroot.

Thanks,
Omar
The other issue that I have noticed, is the helper function for .net 5 needs to be updated to the bellow 
IHtmlHelper instead of HtmlHelper as this it does not exist any more 

![image](https://user-images.githubusercontent.com/35583003/156917811-e00faaae-e879-4c8a-b72a-c362796f19f2.png)

**Comment by robertjf** [comment]
The reason for this is that Umbraco 9 (dotnet Core) references static files from a different path to Umbraco 8.

While we pick the file from a relative filepath based on `/wwwroot/`, the url needs to omit the `/wwwroot` part.
