### ISSUE TITLE
The type or namespace name 'Iconic' could not be found

### ISSUE THREAD

**Issue by sebastiandammark** [skartknet/Iconic#40]
After installing the package through Nuget I get the following message after adding **@using Iconic.Helpers** to my partial view.
Everything seems to be working in backoffice.

I'm running **Umbraco version 12.1.2**

<img width="1012" alt="image" src="https://github.com/skartknet/Iconic/assets/1575483/8c31b48d-b371-4424-8f6f-b58bd491b404">

<img width="1032" alt="image" src="https://github.com/skartknet/Iconic/assets/1575483/f73a2956-4492-4db1-8f7c-a7316fb1cf71">

**Comment by skartknet** [comment]
hi @sebastiandammark , I haven't been able to replicate the issue. Have you upgraded the package or is it a new installation?
