### ISSUE TITLE
Font Awesome 6

### ISSUE THREAD

**Issue by protherj** [skartknet/Iconic#45]
Hello,

I'm trying to setup Iconic with the Font Awesome 6 (Solid) Pre-Configured option.  However, it doesn't appear to be working as I cannot Save the configuration because the Save button is disabled.

My attempt below:

![image](https://github.com/skartknet/Iconic/assets/167112/f9aeb83b-936f-40aa-af7c-7d839ca8ebc6)

I'm using Iconic 5.3 and Umbraco 10.7

Are there additional instructions that I need to follow for Font Awesome 6?

Thanks,
Jason

**Comment by skartknet** [comment]
Hi Jason, it looks like you're missing at least the CSS for the fonts, and maybe the Rules source file if it's different. 

Not sure if it'll help, but you can take a look a the FA5 docs: https://github.com/skartknet/Iconic/tree/master/Documentation/Configuration/FontAwesome5

**Comment by protherj** [comment]
Ah, so it works best when the files are downloaded locally?

**Comment by skartknet** [comment]
Hi @protherj , did you manage to fix this? Can I close the issue?

**Comment by The-algar** [comment]
Hello 
 I've installed Our.Iconic 12.0.0 on Umbraco v13.2.2
 I have no problem seeing FontAwesome 5 (Brands) and FontAwesome 6 (solid) but both FontAwesome 6 (Brands) and FontAwesome 5 (solid) looks like this in the interface
![image](https://github.com/skartknet/Iconic/assets/33525561/035e892f-61cc-4834-8f73-d3ba36e6605a)

Both uses the same setup (the only one that works)
 
![image](https://github.com/skartknet/Iconic/assets/33525561/999d251f-6dd8-476c-8e93-d8c28740f3fc)

Can you help?

**Comment by skartknet** [comment]
This doesn't look like a bug then. I'd recommend you to ask for help on the Umbraco forums instead. Thanks.

https://our.umbraco.com/forum
