### ISSUE TITLE
Umbraco 13 Error when opening package configuration

### ISSUE THREAD

**Issue by BenjaminJepsen** [skartknet/Iconic#47]
I installed Iconic in my Umbraco 13 project and it seems like it is working.

But i get this error when i open the package configuration: https://streamable.com/s29zad

Seems like it is missing a file.
But i haven't touched the Our.Iconic nuget package, so I'm not sure why.
Am i missing something or does this need fixing?

**Comment by skartknet** [comment]
Hi @BenjaminJepsen is this fixed?

**Comment by BenjaminJepsen** [comment]
Hi skartknet
Seems like the error is gone after i updated to version 12, thanks.
