### ISSUE TITLE
Cannot select icon on Element type

### ISSUE THREAD

**Issue by andreaguli14** [skartknet/Iconic#49]
Hello,

I'm trying to setup Iconic with an Element type but when i try to select an icon nothing happens

![image](https://github.com/skartknet/Iconic/assets/10333377/beff2e27-9b9d-4189-a760-c33fce887bdb)

![image](https://github.com/skartknet/Iconic/assets/10333377/549287fd-ea91-4959-ab74-ba6efbb59fcc)

**Comment by skartknet** [comment]
Hi @andreaguli14 ,

What versions of Iconic and Umbraco are you using?

**Comment by skartknet** [comment]
I'll close this for inactivity. Please reopen if needed.
