### ISSUE TITLE
Can't add packages configuration

### ISSUE THREAD

**Issue by jordan-umbrace** [skartknet/Iconic#5]
After adding the Iconic datatype, when clicking on the **'Packages configuration'** 'Add' button, I get redirecten to /umbraco which prevents me from adding a configuration and use the plugin (see image)
![image](https://user-images.githubusercontent.com/16898679/157632125-5248ec7a-2df9-420e-9d83-0e6fd4d126e9.png)

**Comment by skartknet** [comment]
Hi Jordan,

I haven't been able to reproduce the issue. Did you manage to fix it?

**Comment by psmoq** [comment]
There is a problem with Smidge or manifest.json itself, I am able to reproduce this issue (Umbraco 9). The following error appears in the console:

![image](https://user-images.githubusercontent.com/19189902/175493059-3173849b-d617-44c7-b7e2-f3488bf7addb.png)

the link redirects to:
https://code.angularjs.org/1.8.0/docs/error/$controller/ctrlreg?p0=Our.Iconic.Prevalues.Packages
