### ISSUE TITLE
Html Extension Render Icon is not working 

### ISSUE THREAD

**Issue by OmarAlkylaney** [skartknet/Iconic#7]
Dear All,

The Html Extension Render Icon is not yet working due the parameter passed parameter type HtmlHelper is not exist in .NET Core. Instead the code need to be IHtmlHelper. 
`public static IHtmlContent RenderIcon(this IHtmlHelper helper, IHtmlContent icon, object htmlAttributes, params string[] extraClasses)
    {}`

**Comment by robertjf** [comment]
@OmarAlkylaney HtmlHelper does indeed exist in .Net Core >= 5.x in the `Microsoft.AspNetCore.Mvc.ViewFeatures` namespace... however, this is a good pickup.  Fix coming.

**Comment by skartknet** [comment]
Fixed on 3.1.5.
