### ISSUE TITLE
Umbraco V9 404 error when loading css files

### ISSUE THREAD

**Issue by WeewahSlayer1** [skartknet/Iconic#9]
![iconic-datatype](https://user-images.githubusercontent.com/19182176/162902081-ef32f90c-33fe-4c58-9b09-d38f9886f499.JPG)
![css-404](https://user-images.githubusercontent.com/19182176/162902091-3a741202-65ae-49ab-b7bf-ea09abe59829.JPG)

All the steps have been followed (all fields populated), and the css file paths are valid, but we receive a 404 error when the file loads. Please get back to us when you can.

**Comment by skartknet** [comment]
Hi @WeewahSlayer1 , thanks for this. A fix has been deployed as a new version 3.1.5
